import type { FlowModel, Stage } from "../model";
import { usePresenter } from "../presenter";
import type { ValuePreview } from "../types";
import { Chain, PanelHead, SourceList, Term } from "./bits";

/*
 * STATE PARAMETER SECURITY LAB: the exact comparison /callback performs, the
 * attack it stops, and three real ways to make it fail.
 */

interface Props {
  model: FlowModel;
  onRunTamperScenario: () => void;
  onTamperAtBreakpoint: () => void;
  onRemoveState: () => void;
}

export function StateLab({ model, onRunTamperScenario, onTamperAtBreakpoint, onRemoveState }: Props) {
  const { select } = usePresenter();
  const { state } = model;
  const check = state.check?.detail;
  const verdict = check?.verdict ?? null;
  const exchangeAttempted = model.pkce.exchange !== null;
  const tamperedReturned = model.modifications.find((entry) => entry.injection?.id === "tamper-returned-state");
  const removed = model.modifications.find((entry) => entry.injection?.id === "remove-state");

  const narrative: Stage[] = [
    {
      id: "inject",
      label: "An authorization response this session did not ask for arrives",
      actor: "auth",
      status: state.tampered || tamperedReturned || removed ? "done" : verdict && verdict !== "MATCH" ? "done" : "pending",
      entryId: (state.tampered?.entry ?? tamperedReturned ?? removed)?.id ?? null,
      note: state.tampered
        ? "Simulated: the stored state was replaced"
        : tamperedReturned
          ? "Simulated: the returned state was replaced at the breakpoint"
          : removed
            ? "Simulated: the request was sent without state"
            : null,
    },
    {
      id: "callback",
      label: "The browser delivers the callback to /callback",
      actor: "browser",
      status: state.callback ? "done" : "pending",
      entryId: state.callback?.entry.id ?? null,
      note: state.callback?.detail.returnedState ? `state=${state.callback.detail.returnedState.preview}` : state.callback ? "no state in the callback" : null,
    },
    {
      id: "compare",
      label: "The backend compares returned state with stored state",
      actor: "node",
      status: check ? "done" : "pending",
      entryId: state.check?.entry.id ?? null,
      note: check ? `server/src/session.ts checkState() → ${verdict}` : null,
    },
    {
      id: "detect",
      label: verdict && verdict !== "MATCH" ? `${verdict} detected` : "Mismatch detected",
      actor: "node",
      status: verdict === null ? "pending" : verdict === "MATCH" ? "not-needed" : "done",
      entryId: state.check?.entry.id ?? null,
      note: verdict === "MATCH" ? "values matched: nothing to reject" : null,
    },
    {
      id: "reject",
      label: "Request rejected: the code is never exchanged",
      actor: "node",
      status: state.blocked ? "done" : verdict === "MATCH" ? "not-needed" : "pending",
      entryId: state.blocked?.id ?? null,
      note: state.blocked ? "Token exchange NOT attempted" : null,
    },
  ];

  return (
    <section className="state-lab" aria-label="State parameter security lab">
      <PanelHead
        title="State parameter security lab"
        note="state binds the callback to the browser session that started the flow. It is checked BEFORE the code is used."
      />

      <div className={`comparison${verdict ? ` is-${verdict === "MATCH" ? "match" : "mismatch"}` : ""}`}>
        <StateValue label="Generated by the client" value={state.generated?.detail.state ?? null} onInspect={() => state.generated && select(state.generated.entry.id)} />
        <StateValue label="Stored in the server session" value={check?.stored ?? null} onInspect={() => state.check && select(state.check.entry.id)} />
        <StateValue
          label="Returned by the authorization server"
          value={check?.returned ?? state.callback?.detail.returnedState ?? null}
          onInspect={() => state.callback && select(state.callback.entry.id)}
        />
        <div className="comparison-verdict" role="status">
          <span className="verdict-word">{verdict ?? "—"}</span>
          <span className="lede">
            {verdict === null
              ? "No callback in this run yet."
              : verdict === "MATCH"
                ? "Same fingerprint: this callback answers our own request."
                : "Different (or missing): the callback is refused."}
          </span>
        </div>
      </div>

      <dl className="facts-list compact">
        <div>
          <dt>Validation point</dt>
          <dd>
            <code>GET /callback</code> in server/src/routes/auth.ts, via <code>checkState()</code> in server/src/session.ts — before any token request
          </dd>
        </div>
        <div>
          <dt>Token exchange attempted?</dt>
          <dd>{check ? (exchangeAttempted ? "Yes (state matched)" : verdict === "MATCH" ? "Not yet" : "NO — the flow stopped at state validation") : "—"}</dd>
        </div>
        <div>
          <dt>Why the flow stops</dt>
          <dd>Without a match the backend cannot tell whether the code belongs to this user's request, so using it could log the victim in as the attacker.</dd>
        </div>
        <div>
          <dt>Attack prevented</dt>
          <dd>
            CSRF / login CSRF on the redirect endpoint (RFC 6749 §10.12). <Term name="state">What is state?</Term>
          </dd>
        </div>
      </dl>

      <h3>Attack narrative (from this run's real events)</h3>
      <Chain stages={narrative} label="State attack narrative" />

      <div className="experiment">
        <h3>Break it for real</h3>
        <div className="builder-actions">
          <button type="button" className="button" onClick={onRunTamperScenario}>
            Replace the STORED state (scenario 2)
          </button>
          <button type="button" className="button" onClick={onTamperAtBreakpoint}>
            Tamper with the RETURNED state at the validation breakpoint
          </button>
          <button type="button" className="button" onClick={onRemoveState}>
            Send the request WITHOUT state (builder)
          </button>
        </div>
      </div>
      <SourceList
        refs={[
          { file: "server/src/session.ts", symbol: "generateState" },
          { file: "server/src/session.ts", symbol: "checkState" },
          { file: "server/src/routes/auth.ts", symbol: "GET /callback" },
        ]}
      />
    </section>
  );
}

function StateValue({ label, value, onInspect }: { label: string; value: ValuePreview | null; onInspect: () => void }) {
  return (
    <button type="button" className="state-value" onClick={onInspect} disabled={!value}>
      <span className="state-label">{label}</span>
      <code className="state-preview">{value ? value.preview : "—"}</code>
      <span className="state-fp">{value ? `fingerprint ${value.fingerprint}` : "not in this run"}</span>
    </button>
  );
}
